[package]
name = "sl-binding"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
napi = { version = "3.8.1", features = ["async"] }
napi-derive = "3.5.0"

sl-core = { workspace = true }

[build-dependencies]
napi-build = "2.3.1"
