[workspace]
resolver = "3"
members = ["crates/sl-common", "crates/sl-binding"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
sl-common = { path = "./crates/sl-common/" }
