[workspace]
resolver = "3"
members = ["crates/sl-core", "crates/sl-binding"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
sl-core = { path = "./crates/sl-core/" }

[profile.release]
opt-level = "s"
# debug = "full"
# strip = "none"
lto = true
